### ISSUE TITLE
--staged option

### ISSUE THREAD

**Issue by JaKXz** [sheerun/prettier-standard#77]
It would be cool if there was a `--staged` option, like https://github.com/azz/pretty-quick so I don't have to add a pre-commit hook to a project that the team doesn't want hooks on.

**Comment by sheerun** [comment]
Yes, PR is welcome! (it should use lint-staged underneath so partially staged files are supported)

**Comment by sheerun** [comment]
Similar `--changed` and `--since` flags has been introduced in 13.0.0

For now you can use lint-staged to get your behavior

**Comment by JaKXz** [comment]
Would `--changed --since HEAD~1` Do the trick?

**Comment by sheerun** [comment]
`prettier-standard --changed` is enough, but it would also format non-stashed changes.

if you want to format just stashed changes please use lint-staged for now

**Comment by sheerun** [comment]
Also remember that prettier currently has some servere issues with range formatting:

- https://github.com/prettier/prettier/issues/4926
- https://github.com/prettier/prettier/issues/6428

Because of this `--since HEAD` should be currently more stable than `--changes`, but it formats whole contents of changed files, not only changed lines.
